name: Trigger Job

on:
  workflow_dispatch:
    inputs:
      application_name:
        description: 'Name of the application'
        required: true
        default: "xxx"

jobs:
  trigger:
    runs-on: windows-latest

    steps:
    - name: Trigger test.yaml
      run: |
        $headers = @{
            "Accept" = "application/vnd.github.v3+json"
            "Authorization" = "Bearer ${{ secrets.G_TOKEN }}"
        }
        $body = @{
            "ref" = "CICD_Execution"
            "inputs" = @{
                "testType" = "smoke"
                "thread" = "3"
                "customTag" = "@smokeV2"
            }
        } | ConvertTo-Json
        Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yaml/dispatches" -Method Post -Headers $headers -Body $body
      shell: pwsh




# name: Trigger Job

# on:
#   workflow_dispatch:
#     inputs:
#       application_name:
#         description: 'Name of the application'
#         required: true
#         default: "xxx"

# jobs:
#   trigger:
#     runs-on: windows-latest

#     steps:
#     - name: Trigger test.yaml
#       run: |
#         token="${{ secrets.G_TOKEN }}"
#         body=$(jq -n --arg app_name "${{ github.event.inputs.application_name }}" '{"ref":"main","inputs":{"application_name":$app_name}}')
#         curl -X POST -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yaml/dispatches -d "$body"
#       shell: bash



    
      # run: |
      #   set token=${{ secrets.G_TOKEN }}
      #   set body={"ref":"main","inputs":{"application_name":"${{ github.event.inputs.application_name }}"}} 
      #   curl -X POST -H "Authorization: Bearer %token%" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yaml/dispatches -d "{\"ref\":\"main\",\"inputs\":{\"application_name\":\"${{ github.event.inputs.application_name }}\"}}"
      # shell: cmd


      
      # run: |
      #   $token = "${{ secrets.G_TOKEN }}"
      #   $body = @{
      #     "ref" = "main"
      #     "inputs" = @{
      #       "application_name" = "${{ github.event.inputs.application_name }}"
      #     }
      #   } | ConvertTo-Json
      #   Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/test.yaml/dispatches" -Method Post -Headers @{Authorization = "Bearer $token"} -Body $body

